### ISSUE TITLE
Add a "History Last Updated" timestamp to the history barcode

### ISSUE THREAD

**Issue by AlexLipp** [JonnyDawe/UK-Sewage-Map#16]
## Problem 

The overall map shows a timestamp for when the downstream predictions had last been calculated: 
![image](https://github.com/JonnyDawe/UK-Sewage-Map/assets/10188895/99356803-f412-4ba6-9bb2-a9ed1997f2e6)
 
However, we don't show such a timestamp on the "History" tab of the pop-ups. This is a problem because the Thames Water history API is particularly "sticky" and can not-update for a relatively long period of time. Currently, so as not to display "false" information the back-end simply returns **no** history if it is even 30 minutes out of date. However, this results in a fair amount of undesirable downtime. If we can instead display a "last updated" timestamp (with perhaps a visible marker of when that was on the barcode) we can assume that the limitations are being accurately communicated. 

## Solution 
It would be helpful to include a timestamp moving forwards in the pop-up such as:  
![image](https://github.com/JonnyDawe/UK-Sewage-Map/assets/10188895/2952e876-59ab-47a6-93a0-1cb6533995e8). 

The time-stamp which indicates when the discharges were last updated is [already available in the AWS bucket](https://thamessewage.s3.eu-west-2.amazonaws.com/discharges_to_date/timestamp.txt).

**Comment by JonnyDawe** [comment]
@AlexLipp - I have stubbed in the initial logic into a branch here: https://github.com/JonnyDawe/UK-Sewage-Map/tree/%2316-enhancement/history-update-text

Currently I don't have access to the AWS endpoint and am hitting 403 forbidden errors. Would it be possible to have it set up via the cloudfont endpoint as with the other services?

**Comment by AlexLipp** [comment]
Sorry, forgot about the cloudfront distribution. This is the correct URL I believe with the cloudfront endpoint (@sudhir-b I think this is correct?): https://d1kmd884co9q6x.cloudfront.net/discharges_to_date/timestamp.txt

**Comment by AlexLipp** [comment]
Ok, the corrected CloudFront URL should now be here, sorry: https://d1kmd884co9q6x.cloudfront.net/discharges_to_date/timestamp.txt

This URL is sometimes not pointing at anything due to the way it automatically updates, but if you think everything else is set up well I can stop it autodeleting the AWS bucket if an error is returned. Let me know if you think we're ready for that?

**Comment by JonnyDawe** [comment]
Happy for it it be switched over - I'll be able to get it updated in the next day or so!

**Comment by AlexLipp** [comment]
Great, I will sort this shortly.

**Comment by AlexLipp** [comment]
I've updated the back-end to not automatically wipe the last successful history generation. This should mean that there is always a valid history and timestamp present in the bucket (will take a few hours to run through the system I guess) so you can go ahead with updating the front-end.

**Comment by JonnyDawe** [comment]
@AlexLipp - all merged and looks to be working well! I might refine the UI a bit as part of some other tickets!

**Comment by AlexLipp** [comment]
﻿
Amazing, this looks great! Although, seems like when long duration the text overlaps slightly, but this is a minor UI fix (smaller font? Remove some words?)

But yes this is great and gives better idea of confidence in history + much less downtime.

[image0.jpeg]

On 1 Jun 2024, at 14:07, Jonny Dawe ***@***.***> wrote:

﻿

@AlexLipp<https://github.com/AlexLipp> - all merged and looks to be working well! I might refine the UI a bit as part of some other tickets!

**Comment by JonnyDawe** [comment]
@AlexLipp yep I spotted that on mobile! Will tweak the layout to make it wrap better.

Unfortunately I'm seeing that the failed to load discharge warning has returned indicating failed requests to the endpoint?

**Comment by JonnyDawe** [comment]
Actually it seems to have come back... I may have had an old page cached

**Comment by AlexLipp** [comment]
Yes I can’t reproduce that bug. I’ll keep an eye out in future to see if it reoccurs. Just from having checked this a lot I’m seeing much less downtime than previously so I think it’s working ok. I’ll check the logs too (need to get that set up to have them emailed to a server rather than only stored locally)

On 1 Jun 2024, at 17:22, Jonny Dawe ***@***.***> wrote:

﻿

@AlexLipp<https://github.com/AlexLipp> yep I spotted that on mobile! Will tweak the layout to make it wrap better.

Unfortunately I'm seeing that the failed to load discharge warning has returned indicating failed requests to the endpoint?
